### Text Pre-processing

In [1]:
import pandas as pd
import sys
import csv
import re
maxInt = sys.maxsize

while True:
    try:
        csv.field_size_limit(maxInt)
        break
    except OverflowError:
        maxInt = int(maxInt/10)

In [2]:
df_extracted = pd.read_csv('df_extracted.csv', engine='python', encoding='utf-8', error_bad_lines=False)

In [3]:
df_extracted.describe()

         Unnamed: 0         count
count  18977.000000  1.897700e+04
mean   11927.675344  9.184705e+04
std     6883.190923  1.599096e+05
min        0.000000  1.010000e+02
25%     5946.000000  1.025200e+04
50%    11961.000000  2.830500e+04
75%    17885.000000  1.055390e+05
max    23795.000000  2.708538e+06

In [4]:
df_extracted

,Unnamed: 0,file_name,clean_text,count
0,0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf.txt,CORPORATE SOCIAL RESPONSIBILITY PERFORMANCE RE...,29122
1,1,20150416_COP_N°5_EN.pdf.txt,Sustainable development the energy that fuels ...,11939
2,2,2017_report_-_FINAL__UNLOCKED.pdf.txt,The whole or any part of this work may not be ...,226975
3,3,COP_Report_SMART_-_Apr_2013_final.pdf.txt,PTSinarMasAgro Resources andTechnology TbkGlob...,37025
4,4,cop_ETS_2019.pdf.txt,Eser Contracting and Industry Co. Inc. Communi...,35188
...,...,...,...,...
18972,23789,CSR_Report_2014.pdf.txt,AH Industries Corporate Social R esponsibility...,39306
18973,23792,Nilorngruppen_Sustainability_report.pdf.txt,1More fit for the future SUSTAINABILITY REPORT...,112118
18974,23793,MM_CSR_2018.pdf.txt,ANNUAL CORPORATE SOCIAL RESPONSIBILITY REPORT ...,39360
18975,23794,AmatheonAgri-COP-2017.pdf.txt,01AMATHEON AGRI COMMUNICATION ON PROGRESS 2017...,21804
18976,23795,Letter_COP_CEO_Oct2014.pdf.txt,24 th October 2014 To our stakeholders I am pl...,586

In [5]:
#Remove .txt extension on the file_name column
df_extracted['file_name'] = df_extracted['file_name'].str.replace(r'.txt$', '')
df_extracted

,Unnamed: 0,file_name,clean_text,count
0,0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf,CORPORATE SOCIAL RESPONSIBILITY PERFORMANCE RE...,29122
1,1,20150416_COP_N°5_EN.pdf,Sustainable development the energy that fuels ...,11939
2,2,2017_report_-_FINAL__UNLOCKED.pdf,The whole or any part of this work may not be ...,226975
3,3,COP_Report_SMART_-_Apr_2013_final.pdf,PTSinarMasAgro Resources andTechnology TbkGlob...,37025
4,4,cop_ETS_2019.pdf,Eser Contracting and Industry Co. Inc. Communi...,35188
...,...,...,...,...
18972,23789,CSR_Report_2014.pdf,AH Industries Corporate Social R esponsibility...,39306
18973,23792,Nilorngruppen_Sustainability_report.pdf,1More fit for the future SUSTAINABILITY REPORT...,112118
18974,23793,MM_CSR_2018.pdf,ANNUAL CORPORATE SOCIAL RESPONSIBILITY REPORT ...,39360
18975,23794,AmatheonAgri-COP-2017.pdf,01AMATHEON AGRI COMMUNICATION ON PROGRESS 2017...,21804
18976,23795,Letter_COP_CEO_Oct2014.pdf,24 th October 2014 To our stakeholders I am pl...,586

In [6]:
# Lower all text contents
df_extracted['text'] = df_extracted['text'].str.lower()
df_extracted

KeyError: 'text'

In [13]:
# replace special special character
df_extracted['text'] = df_extracted['text'].str.replace("\n","").replace("\t"," ").replace("\x0c"," ").replace(".",". ").replace(',',"").replace("\r\n"," ")
df_extracted['text'] = df_extracted['text'].str.replace("\r"," ")
df_extracted

,file_name,text
0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf,corporate social responsibility performance ...
1,20150416_COP_N°5_EN.pdf,"sustainable development, the energy that f..."
2,2017_report_-_FINAL__UNLOCKED.pdf,˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚ˆ˝˝˚˜˜˜˚˛˝˙˝ˆ˛˝ˇˆˆ...
3,COP_Report_SMART_-_Apr_2013_final.pdf,ptsinarmasagroresourcesandtechnologytbkglobalc...
4,cop_ETS_2019.pdf,eser contracting and industry co.inc. comm...
...,...,...
23791,JCCCSA_-_COMUNICACIÓN_DE_PROGRESO_PARA_EL_PACT...,
23792,Nilorngruppen_Sustainability_report.pdf,_1more fit for the futuresustainability report...
23793,MM_CSR_2018.pdf,annual corporate social responsibility report2...
23794,AmatheonAgri-COP-2017.pdf,01amatheon agricommunicationon progress 2017gr...
23795,Letter_COP_CEO_Oct2014.pdf,24th october 2014 to our stakehol...

In [ ]:
df_extracted.to_csv('df_extracted_cleaned.csv')

In [3]:
pd.read_csv('df_extracted_cleaned.csv', engine='python', encoding='utf-8', error_bad_lines=False)

,Unnamed: 0,file_name,text,Matches
0,0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf.txt,corporate social responsibility performance...,"{'DATE': '2019', 'ORG': 'saint léonard - franc..."
1,1,20150416_COP_N°5_EN.pdf.txt,"sustainable development, the energy th...","{'DATE': '2015', 'ORG': 'asnières - sur - sein..."
2,2,2017_report_-_FINAL__UNLOCKED.pdf.txt,˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚ˆ˝˝˚˜˜˜˚˛˝˙˝ˆ˛˝ˇˆˆ...,"{'ORDINAL': 'third', 'ORG': 'llc', 'DATE': '22..."
3,3,COP_Report_SMART_-_Apr_2013_final.pdf.txt,ptsinarmasagro resources andtechnology tbkglob...,{'PERSON': 'thispolicyalsoappliestoemployees w...
4,4,cop_ETS_2019.pdf.txt,eser contracting and industry co.inc. ...,"{'CARDINAL': '10', 'ORG': 'subje ct', 'DATE': ..."
5,5,Orkla_Annual_Report_2014.pdf.txt,annual report2014 contents03 about orkla 06 me...,"{'DATE': '© 2014', 'ORG': 'no-0276 oslo', 'CAR..."
6,6,COP_TT-SE_20140318.pdf.txt,NaN,{}
7,7,Tabadlab Communication on Progress .pdf.txt,"!!""#""$%""#&'()*""+,&-).)+,$ /&0,11""2)2,&3%44(...","{'MONEY': '#""$%', 'ORG': '& &&&&&&', 'WORK_OF_..."
8,8,GRUPO_CLARIN_COP_2017.pdf.txt,1 company name : grupo clarín s.a. co...,"{'CARDINAL': '24,419.13', 'ORG': 'm3 1..."
9,9,2020_report_en.pdf.txt,integrated solutions fora better life 2020 int...,"{'DATE': '2021', 'ORG': 'fsc tm(forest steward..."