### Text Pre-processing

In [1]:
import pandas as pd
import sys
import csv
import re
maxInt = sys.maxsize

while True:
    try:
        csv.field_size_limit(maxInt)
        break
    except OverflowError:
        maxInt = int(maxInt/10)

In [2]:
df_extracted = pd.read_csv('df_extracted.csv', engine='python', encoding='utf-8', error_bad_lines=False)

In [3]:
df_extracted.describe()

        Unnamed: 0  Unnamed: 0.1
count  1000.000000   1000.000000
mean    499.500000    499.500000
std     288.819436    288.819436
min       0.000000      0.000000
25%     249.750000    249.750000
50%     499.500000    499.500000
75%     749.250000    749.250000
max     999.000000    999.000000

In [4]:
df_extracted

,Unnamed: 0,Unnamed: 0.1,file_name,text
0,0,0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf,corporate social responsibility performance...
1,1,1,20150416_COP_N°5_EN.pdf,"sustainable development, the energy th..."
2,2,2,2017_report_-_FINAL__UNLOCKED.pdf,˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚ˆ˝˝˚˜˜˜˚˛˝˙˝ˆ˛˝ˇˆˆ...
3,3,3,COP_Report_SMART_-_Apr_2013_final.pdf,ptsinarmasagro resources andtechnology tbkglob...
4,4,4,cop_ETS_2019.pdf,eser contracting and industry co.inc. ...
...,...,...,...,...
995,995,995,Global_Compact_Initiative_March_2012_update.pdf,"!""!!""#$%""&'#()%*+&,-.+.%+./0 1&20++03&#4&50%44..."
996,996,996,Novitag_cop_2015.pdf,novitag be irut 21/10/2015 a s the ...
997,997,997,1st_Communication_on_Progress_EFSA_eng.pdf,"eurofinsapaseo de la castellana, 9128046 madri..."
998,998,998,RELATIONAL_UN_COP.pdf,NaN
999,999,999,Sustainability_report_2019_final.pdf,1trioplast sustainability report 2019 2triop...

In [5]:
#Remove .txt extension on the file_name column
df_extracted['file_name'] = df_extracted['file_name'].str.replace(r'.txt$', '')
df_extracted

/Users/ohikendoit/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

,Unnamed: 0,Unnamed: 0.1,file_name,text
0,0,0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf,corporate social responsibility performance...
1,1,1,20150416_COP_N°5_EN.pdf,"sustainable development, the energy th..."
2,2,2,2017_report_-_FINAL__UNLOCKED.pdf,˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚ˆ˝˝˚˜˜˜˚˛˝˙˝ˆ˛˝ˇˆˆ...
3,3,3,COP_Report_SMART_-_Apr_2013_final.pdf,ptsinarmasagro resources andtechnology tbkglob...
4,4,4,cop_ETS_2019.pdf,eser contracting and industry co.inc. ...
...,...,...,...,...
995,995,995,Global_Compact_Initiative_March_2012_update.pdf,"!""!!""#$%""&'#()%*+&,-.+.%+./0 1&20++03&#4&50%44..."
996,996,996,Novitag_cop_2015.pdf,novitag be irut 21/10/2015 a s the ...
997,997,997,1st_Communication_on_Progress_EFSA_eng.pdf,"eurofinsapaseo de la castellana, 9128046 madri..."
998,998,998,RELATIONAL_UN_COP.pdf,NaN
999,999,999,Sustainability_report_2019_final.pdf,1trioplast sustainability report 2019 2triop...

In [6]:
# Lower all text contents
df_extracted['text'] = df_extracted['text'].str.lower()
df_extracted

,Unnamed: 0,Unnamed: 0.1,file_name,text
0,0,0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf,corporate social responsibility performance...
1,1,1,20150416_COP_N°5_EN.pdf,"sustainable development, the energy th..."
2,2,2,2017_report_-_FINAL__UNLOCKED.pdf,˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚ˆ˝˝˚˜˜˜˚˛˝˙˝ˆ˛˝ˇˆˆ...
3,3,3,COP_Report_SMART_-_Apr_2013_final.pdf,ptsinarmasagro resources andtechnology tbkglob...
4,4,4,cop_ETS_2019.pdf,eser contracting and industry co.inc. ...
...,...,...,...,...
995,995,995,Global_Compact_Initiative_March_2012_update.pdf,"!""!!""#$%""&'#()%*+&,-.+.%+./0 1&20++03&#4&50%44..."
996,996,996,Novitag_cop_2015.pdf,novitag be irut 21/10/2015 a s the ...
997,997,997,1st_Communication_on_Progress_EFSA_eng.pdf,"eurofinsapaseo de la castellana, 9128046 madri..."
998,998,998,RELATIONAL_UN_COP.pdf,NaN
999,999,999,Sustainability_report_2019_final.pdf,1trioplast sustainability report 2019 2triop...

In [7]:
# replace special special character
df_extracted['text'] = df_extracted['text'].str.replace("\n"," ").replace("\t"," ").replace("\x0c"," ").replace(".",". ").replace(',',"").replace("\r\n"," ")
df_extracted['text'] = df_extracted['text'].str.replace("\r"," ")
df_extracted

,Unnamed: 0,Unnamed: 0.1,file_name,text
0,0,0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf,corporate social responsibility performance...
1,1,1,20150416_COP_N°5_EN.pdf,"sustainable development, the energy th..."
2,2,2,2017_report_-_FINAL__UNLOCKED.pdf,˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚ˆ˝˝˚˜˜˜˚˛˝˙˝ˆ˛˝ˇˆˆ...
3,3,3,COP_Report_SMART_-_Apr_2013_final.pdf,ptsinarmasagro resources andtechnology tbkglob...
4,4,4,cop_ETS_2019.pdf,eser contracting and industry co.inc. ...
...,...,...,...,...
995,995,995,Global_Compact_Initiative_March_2012_update.pdf,"!""!!""#$%""&'#()%*+&,-.+.%+./0 1&20++03&#4&50%44..."
996,996,996,Novitag_cop_2015.pdf,novitag be irut 21/10/2015 a s the ...
997,997,997,1st_Communication_on_Progress_EFSA_eng.pdf,"eurofinsapaseo de la castellana, 9128046 madri..."
998,998,998,RELATIONAL_UN_COP.pdf,NaN
999,999,999,Sustainability_report_2019_final.pdf,1trioplast sustainability report 2019 2triop...

In [8]:
df_extracted = df_extracted[:500]

In [9]:
df_extracted.to_csv('df_extracted.csv')

In [10]:
pd.read_csv('df_extracted.csv', engine='python', encoding='utf-8', error_bad_lines=False)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,file_name,text
0,0,0,0,OLVEA - OLVEAct Now Report - EN - 2019-20.pdf,corporate social responsibility performance...
1,1,1,1,20150416_COP_N°5_EN.pdf,"sustainable development, the energy th..."
2,2,2,2,2017_report_-_FINAL__UNLOCKED.pdf,˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚˛˚˝˙˜˚ˆ˝˝˚˙˜˚ˆ˝˝˚˜˜˜˚˛˝˙˝ˆ˛˝ˇˆˆ...
3,3,3,3,COP_Report_SMART_-_Apr_2013_final.pdf,ptsinarmasagro resources andtechnology tbkglob...
4,4,4,4,cop_ETS_2019.pdf,eser contracting and industry co.inc. ...
...,...,...,...,...,...
495,495,495,495,UN_Global_Compact_-_CEO_Letter.pdf,"10 march 2020 to our stakeholders , i a..."
496,496,496,496,Embraer_Annual_Report_2015_English.pdf,2015annualreportannual report 201501index flyi...
497,497,497,497,Eczacibasi_Group_2013_Sustainability_Report.pdf,NaN
498,498,498,498,2020annualreport.pdf,edc 2020 annual report business as unusual e...
499,499,499,499,Frontier's_committment_to_UN_Global_Compact.pdf,frontier economics 1 communication of ...